CATALOGUE_HOST: catalogue.backend-{{ environment }}.vinodh.site
USER_HOST: user.backend-{{ environment }}.vinodh.site
CART_HOST: cart.backend-{{ environment }}.vinodh.site
SHIPPING_HOST: shipping.backend-{{ environment }}.vinodh.site
PAYMENT_HOST: payment.backend-{{ environment }}.vinodh.site