CART_HOST: cart.backend-{{ environment }}.vinodh.site
USER_HOST: user.backend-{{ environment }}.vinodh.site
RABBITMQ_HOST: rabbitmq-{{ environment }}.vinodh.site
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123